templates:
  - posix_c:
    - dbus_client:
      - AUTHORS.template
      - autogen.template
      - ChangeLog.template
      - configure.template
      - COPYING.template
      - Makefile.template
      - NEWS.template
      - README.template
      - src/main.template
      - src/Makefile.template
    - dbus_server:
      - AUTHORS.template
      - autogen.template
      - ChangeLog.template
      - configure.template
      - COPYING.template
      - Makefile.template
      - NEWS.template
      - README.template
      - src/main.template
      - src/Makefile.template
  - posix_cxx:
    - dbus_client:
      - AUTHORS.template
      - autogen.template
      - ChangeLog.template
      - configure.template
      - COPYING.template
      - Makefile.template
      - NEWS.template
      - README.template
      - po/ChangeLog.template
      - po/LINGUAS.template
      - po/POTFILES.template
      - src/main.template
      - src/Makefile.template
    - dbus_server:
      - AUTHORS.template
      - autogen.template
      - ChangeLog.template
      - configure.template
      - COPYING.template
      - Makefile.template
      - NEWS.template
      - README.template
      - po/ChangeLog.template
      - po/LINGUAS.template
      - po/POTFILES.template
      - src/main.template
      - src/Makefile.template
  - posix_py:
    - dbus_client:
      - AUTHORS.template
      - autogen.template
      - ChangeLog.template
      - configure.template
      - COPYING.template
      - Makefile.template
      - NEWS.template
      - README.template
      - src/dbus_client.template
      - src/Makefile.template
    - dbus_server:
      - AUTHORS.template
      - autogen.template
      - ChangeLog.template
      - configure.template
      - COPYING.template
      - Makefile.template
      - NEWS.template
      - README.template
      - src/dbus_server.template
      - src/Makefile.template
modules:
  - posix_c:
    - dbus_client:
      - AUTHORS
      - autogen.sh
      - ChangeLog
      - configure.ac
      - COPYING
      - Makefile.am
      - NEWS
      - README.md
      - src/main.c
      - src/Makefile.am
    - dbus_server:
      - AUTHORS
      - autogen.sh
      - ChangeLog
      - configure.ac
      - COPYING
      - Makefile.am
      - NEWS
      - README.md
      - src/main.c
      - src/Makefile.am
  - posix_cxx:
    - dbus_client:
      - AUTHORS
      - autogen.sh
      - ChangeLog
      - configure.ac
      - COPYING
      - Makefile.am
      - NEWS
      - README.md
      - po/ChangeLog
      - po/LINGUAS
      - po/POTFILES.in
      - src/main.cc
      - src/Makefile.am
    - dbus_server:
      - AUTHORS
      - autogen.sh
      - ChangeLog
      - configure.ac
      - COPYING
      - Makefile.am
      - NEWS
      - README.md
      - po/ChangeLog
      - po/LINGUAS
      - po/POTFILES.in
      - src/main.cc
      - src/Makefile.am
  - posix_py:
    - dbus_client:
      - AUTHORS
      - autogen.sh
      - ChangeLog
      - configure.ac
      - COPYING
      - Makefile.am
      - NEWS
      - README.md
      - src/dbus_client.py
      - src/Makefile.am
    - dbus_server:
      - AUTHORS
      - autogen.sh
      - ChangeLog
      - configure.ac
      - COPYING
      - Makefile.am
      - NEWS
      - README.md
      - src/dbus_client.py
      - src/Makefile.am
