# @info   gen_py_pro ver.2.0
# @author Vladimir Roncevic elektron.ronca@gmail.com
# @brief  Process this file with automake to produce Makefile.in.

# The main script
bin_SCRIPTS = ${PRO}.py

# Directory where .class files will be installed
${PRO}dir = $$(pythondir)/${PRO}

${PRO}_PYTHON = \
    ${PRO}.py
