name: gen_dbus install python2 package
on:
  push:
    branches: [ main ]
    paths:
      - 'gen_dbus/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'gen_dbus/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '2.x'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt
    - name: build and publish
      run: |
        python setup.py --github sdist bdist_wheel
