name: gen_dbus toc generator
on:
  push:
    paths:
      - '**.md'
jobs:
  generateTOC:
    name: gen_dbus toc generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
